import '@/styles/globals.css'
import Head from 'next/head'
import { Provider } from 'react-redux';
import { wrapper } from '../State/Store';
import { SessionProvider } from "next-auth/react";
import {Nav} from '@/component/Nav';
 function App({ Component, pageProps: { session, ...pageProps }}) {
  const { store, props } = wrapper.useWrappedStore(pageProps);
  return (
  <SessionProvider session={session}>
    <Head>
        <title>Hashify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <Provider store={store}>
      <div className="container text-gray-200 mx-auto max-w-full  bg-gray-900 h-screen">
          <Nav/>
          <div className=" text-white ">
            <Component {...pageProps} />
        </div>
      </div>
    </Provider>
  </SessionProvider>
  )
}
export default App